services:
  app-db:
    image: postgres:16
    container_name: job_app_db
    environment:
      POSTGRES_DB: jobs
      POSTGRES_USER: jobs
      POSTGRES_PASSWORD: jobs
    ports:
      - "5433:5432"
    volumes:
      - app_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U jobs -d jobs"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
    container_name: job_api
    environment:
      DB_URL: ${DB_URL_DOCKER:-postgresql+psycopg2://jobs:jobs@app-db:5432/jobs}
    ports:
      - "8000:8000"
    depends_on:
      app-db:
        condition: service_healthy

  airflow-db:
    image: postgres:16
    container_name: airflow_db
    environment:
      POSTGRES_DB: airflow
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
    volumes:
      - airflow_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow -d airflow"]
      interval: 10s
      timeout: 5s
      retries: 5

  airflow-init:
    image: apache/airflow:2.10.5-python3.11
    container_name: airflow_init
    depends_on:
      airflow-db:
        condition: service_healthy
      api:
        condition: service_started
    environment: &airflow_env
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-db:5432/airflow
      JOB_API_BASE_URL: ${JOB_API_BASE_URL:-http://api:8000}
      CRAWL_TITLE: ${CRAWL_TITLE:-data scientist}
      CRAWL_LOCATION: ${CRAWL_LOCATION:-Paris}
      CRAWL_COUNT: "${CRAWL_COUNT:-30}"
      AIRFLOW_UID: ${AIRFLOW_UID:-50000}
    volumes:
      - ./src/dags:/opt/airflow/dags
      - airflow_logs:/opt/airflow/logs
      - airflow_plugins:/opt/airflow/plugins
    command: >
      bash -c "
      airflow db migrate &&
      airflow users create
      --username admin
      --password admin
      --firstname Airflow
      --lastname Admin
      --role Admin
      --email admin@example.com || true
      "

  airflow-webserver:
    image: apache/airflow:2.10.5-python3.11
    container_name: airflow_webserver
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    environment: *airflow_env
    volumes:
      - ./src/dags:/opt/airflow/dags
      - airflow_logs:/opt/airflow/logs
      - airflow_plugins:/opt/airflow/plugins
    ports:
      - "8080:8080"
    command: webserver

  airflow-scheduler:
    image: apache/airflow:2.10.5-python3.11
    container_name: airflow_scheduler
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    environment: *airflow_env
    volumes:
      - ./src/dags:/opt/airflow/dags
      - airflow_logs:/opt/airflow/logs
      - airflow_plugins:/opt/airflow/plugins
    command: scheduler

volumes:
  app_db_data:
  airflow_db_data:
  airflow_logs:
  airflow_plugins:
